name: Build and Push Chatwoot

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: kirodewal/reseller

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true

          tags: |
            ${{ vars.DOCKER_USER }}/chatwoot:v4.16.1
            ${{ vars.DOCKER_USER }}/chatwoot:latest

          build-args: |
            GIT_SHA=${{ github.sha }}

          cache-from: type=gha
          cache-to: type=gha,mode=max
